api/urls.py
from rest_framework.urlpatterns import format_suffix_patterns
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from hospital import views as hospital_view
from users import views as users_view
from django.conf.urls import url

# Create a router and register our viewsets with it.

router = DefaultRouter()

u_list = users_view.UserViewSet.as_view({
    'get': 'list',
    'post': 'create'
})
user_detail = users_view.UserViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})
profile_list = users_view.ProfileViewSet.as_view({
    'get': 'list',
    'post': 'create'
})
profile_detail = users_view.ProfileViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})
hospitals_list = hospital_view.HospitalsViewSet.as_view({
    'get': 'list',
    'post': 'create'
})
hospitals_detail = hospital_view.HospitalsViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})

student_list = users_view.StudentViewSet.as_view({
    'get': 'list',
    'post': 'create'
})
student_detail = users_view.StudentViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})
appointments_list = users_view.AppointmentsViewSet.as_view({
    'get': 'list',
    'post': 'create'
})
appointments_detail = users_view.AppointmentsViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})
prescriptions_list = users_view.PrescriptionViewSet.as_view({
    'get': 'list',
    'post': 'create'
})
prescriptions_detail = users_view.PrescriptionViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})
doctor_list = users_view.DoctorsViewSet.as_view({
    'get': 'list',
    'post': 'create'
})
doctor_detail = users_view.DoctorsViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})
# The API URLs are now determined automatically by the router.
urlpatterns = format_suffix_patterns([
    path('', users_view.api_root),
    path('hospitals', hospitals_list, name='hospitals'),
    path('hospitals/<pk>/', hospitals_detail),
    path('students', student_list, name='students'),
    path('students/<pk>/', student_detail),
    path('doctors', doctor_list, name='doctors'),
    path('doctors/<pk>/', doctor_detail),
    path('users', u_list, name='users'),
    path('users/<pk>/', user_detail),
    path('profiles', profile_list, name='profiles'),
    path('profiles/<pk>/', profile_detail),
    path('appointments', appointments_list, name='appointments'),
    path('appointments/<pk>/', appointments_detail),
    path('prescriptions', prescriptions_list, name='prescriptions'),
    path('prescriptions/<pk>/', prescriptions_detail),
])

restapi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views # for login logout
from .views import login, sample_api, loginPage, logout
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('hospital.urls')),
    path('api/', include('api.urls')),
    path('api/login', login, name='api_login'),
    path('', loginPage),
    path('login', loginPage),

    path('api/sampleapi', sample_api),

    # path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('logout/', logout, name='logout'),

]
urlpatterns += [
    path('api-auth/', include('rest_framework.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from rest_framework.urlpatterns import format_suffix_patterns
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views
from django.conf.urls import url

urlpatterns = format_suffix_patterns([
    path('users-list', views.users_listing, name='users_listing'),
    path('users/add', views.add_user, name='add_user'),
    path('users/<int:id>/', views.edit_user, name='edit_user'),
    path('users/profile/<int:id>/', views.user_profile, name='user_profile'),
    path('users-dashboard', views.users_dashboard, name='users_dashboard'),
    path('appointment/add', views.add_appointment, name='add_appointment'),
    path('appointments-list', views.appointments_listing, name='appointments_listing'),
    path('appointments-schedule/', views.AppointmentCalendar.as_view(), name='appointments_schedule'),
    path('appointments/<int:id>/', views.appointment_detail, name='appointment_detail_page'),
    path('appointments/edit/<int:id>/', views.edit_appointment, name='edit_appointment'),
    #path('appointments/<int:appointment_id>/prescriptions/add/',views.add_prescriptions, name='add_prescriptions'),
    path('appointments/<int:appointment_id>/prescriptions/add/',views.add_prescriptions_info, name='add_prescriptions_info'),
    path('save_prescriptions_info/',views.save_prescriptions_info, name='save_prescriptions_info'),
    path('delete_prescriptions_info/',views.delete_prescriptions_info, name='delete_prescriptions_info'),
    path('prescriptions-list', views.prescriptions_listings, name='prescriptions_listing'),
    path('prescriptions/add', views.add_prescriptions, name='add_prescriptionsfordoctor'),


    path('prescriptions/<int:id>/', views.prescriptions_detail, name='prescriptions_detail_page'),
    path('prescriptions/<int:id>/edit/', views.edit_prescriptions, name='edit_prescriptions'),
])

users/models.py
from django.db import models
from pygments.lexers import get_all_lexers
from pygments.styles import get_all_styles
from django.contrib.auth.models import User
from pygments.lexers import get_lexer_by_name
from pygments.formatters.html import HtmlFormatter
from PIL import Image # resize image

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
	title = models.CharField(max_length=100, blank=True, null=True)
	GENDER_CHOICES = (
		('male', 'Male'),
		('female', 'Female'),
	)
	gender = models.CharField(choices=GENDER_CHOICES, blank=True, null=True, max_length=10)
	designation =  models.CharField(max_length=250, blank=True, null=True)
	qualification = models.CharField(max_length=250, blank=True, null=True)
	experience = models.CharField(max_length=250, blank=True, null=True)
	primary_hospital = models.ForeignKey("hospital.Hospital", on_delete=models.SET_NULL, blank=True, null=True)                                    
	secondary_hospital = models.ForeignKey("hospital.Hospital", on_delete=models.SET_NULL, related_name='secondary_hospital',blank=True, null=True)                                    
	specialty = models.CharField(max_length=250, blank=True, null=True)
	mobile_no = models.CharField(max_length=25, blank=True, null=True)
	session_1_start = models.TimeField(null=True, blank=True)
	session_1_end = models.TimeField(null=True, blank=True)
	session_2_start = models.TimeField(null=True, blank=True)
	session_2_end = models.TimeField(null=True, blank=True)
	avatar = models.ImageField(default='default.png',upload_to='profile')
	MARTIAL_STATUS = (
		('married', 'Married'),
		('unmarried', 'Unmarried'),
		('windowed', 'Widowed'),
	)
	martial_status = models.CharField(choices=MARTIAL_STATUS, blank=True, null=True, max_length=10)
	weight = models.CharField(max_length=250, blank=True, null=True)
	height = models.CharField(max_length=250, blank=True, null=True)
	diseases  = models.CharField(max_length=250, blank=True, null=True)
	allergies = models.CharField(max_length=250, blank=True, null=True)
	BLOOD_TYPES = (
		('O+', 'O-Positive'),
		('O-', 'O-Negative'),
		('A+', 'A-Positive'),
		('A-', 'A-Negative'),
		('AB+', 'AB-Positive'),
		('AB-', 'AB-Negative'),
	)
	blood_type = models.CharField(choices=BLOOD_TYPES, blank=True, null=True, max_length=4)
	notes = models.TextField(blank=True, null=True)
	created_date = models.DateTimeField(auto_now_add=True)
	modified_date = models.DateTimeField(auto_now=True)
	class Meta:
		ordering = ('created_date',)

	def __str__(self): # converting obj
		return f'{self.user.username} Profile'



class Appointment(models.Model):
	student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='student')    
	doctor = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='doctor', blank=True, null=True)
	refer_to = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='refer_to', blank=True, null=True)
	datetime = models.DateTimeField()
	disease = models.TextField()
	notes = models.TextField(blank=True, null=True)
	STATUS_CHOICES = (
		('N', 'New'),
		('P', 'Processed'),
		('C', 'Cancel'),
	)
	status = models.CharField(choices=STATUS_CHOICES, max_length=2, default='N')
	# status = models.BooleanField(default=True)
	created_date = models.DateTimeField(auto_now_add=True)
	modified_date = models.DateTimeField(auto_now=True)
	def __str__(self): # converted obj
		return f'{self.student.username}- App. # {self.id}'


class Prescription(models.Model):
	appointment = models.OneToOneField(Appointment, on_delete=models.CASCADE, primary_key=True)
	how_to_use = models.TextField(blank=True, null=True)
	medicine_name = models.CharField(max_length=250, blank=True, null=True)
	medicine_type = models.ForeignKey("hospital.MedicineType", on_delete=models.SET_NULL, blank=True, null=True)
	edit_by = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='edit_by', blank=True, null=True)
	created_date = models.DateTimeField(auto_now_add=True)
	modified_date = models.DateTimeField(auto_now=True)
	def __str__(self): # convert obj
		managed = False
		return f'{self.appointment.student.username} Appointment with {self.appointment.doctor.username} '

class Prescription_info(models.Model):
	appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE, related_name='appointment')
	how_to_use = models.TextField(blank=True, null=True)
	medicine_name = models.CharField(max_length=250, blank=True, null=True)
	medicine_type = models.ForeignKey("hospital.MedicineType", on_delete=models.SET_NULL, blank=True, null=True)
	created_date = models.DateTimeField(auto_now_add=True)
	edit_by = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='edit_user', blank=True, null=True)
	modified_date = models.DateTimeField(auto_now=True)
	def __str__(self): # convert obj
		managed = False
		return f'{self.medicine_name}'
	

users/templates/users/user/add_profile.html
{% load crispy_forms_tags %}
 <div id="user_profile" class="tab-pane container fade">
    <div class="card-block">
        <form method="POST" class="profile_form" action="{% url app %}" enctype="multipart/form-data">
            <fieldset class="form-group">
                {% crispy profile_form %}
                <div class="form-group">
                    <button class="btn btn-info save-profile" type="submit">Save </button>
                    <p class="text-danger" id="error"> </p>
                </div>
            </fieldset>
        </form>
    </div>
</div>

users/templates/users/user/add_user.html
{% load crispy_forms_tags %}
<div id="basic_info" class="tab-pane container active">
    <div class="card-block">
        <form method="POST" class="form" action="{% url app %}" enctype="multipart/form-data">
            <fieldset class="form-group">
                {% crispy form %}
                <div class="form-group">
                    {% if profile_form %}
                    <button class="btn btn-info save-basic next" type="submit">Next </button>
                    {% else %}
                    <button class="btn btn-info save-basic" type="submit">Save </button>
                    {% endif %}
                    <p class="text-danger" id="error"> </p>
                </div>
            </fieldset>
        </form>
    </div>
</div>

users/templates/users/user/form.html
{% extends "users/base.html" %}
{% load static %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 p-0">
            <div class="main-header">
                <h4>{{ app|capfirst }}</h4>
                <ol class="breadcrumb breadcrumb-title breadcrumb-arrow">
                    <li class="breadcrumb-item"><a href="/"><i class="icofont icofont-home"></i></a>
                    </li>
                    <li class="breadcrumb-item"><a href="#"> {{ app|capfirst }} </a>
                    </li>
                </ol>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <legend class="border-bottom mb-4">{% if user_obj  %} Edit  {{ app|capfirst }}  {% else %} Add {{ app|capfirst }} {% endif %}</legend>
                    <ul class="nav nav-tabs md-tabs " role="tablist">
                      <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#basic_info" role="tab">
                        <i class="icofont icofont-info-circle"></i> Basic Info</a>
                        <div class="slide"></div>
                      </li>
                      {% if profile_form %}
                      <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#user_profile" role="tab">
                        <i class="icofont icofont-ui-user"></i> Profile</a>
                        <div class="slide"></div>
                      </li>
                      {% endif %}
                    </ul>
                    <div class="tab-content">
                        {% include "users/user/add_user.html" %}
                        {% if profile_form %}
                            {% include "users/user/add_profile.html" %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block footer %}
<script>
    jQuery(document).ready(function($) {
        // add image tag to show choosen avatar
        $('#id_avatar').before('<img class="img-responsive col-sm-1" id="avatar" src="{{user_obj.profile.avatar.url}}" />');
        avatar_url = null;
        function Validate() {
            var password = document.getElementById("id_password1").value;
            var confirmPassword = document.getElementById("id_password2").value;
            if (password != confirmPassword) {
                $.toaster({priority: 'danger', title: 'Error', message:'Password and Confirm Password mismatched' });
                return false;
            }

            return true;
        }
        function readFile() {
          if (this.files && this.files[0]) {
            var FR= new FileReader();
            FR.addEventListener("load", function(e) {
              document.getElementById("avatar").src = e.target.result;
              $('#avatar').show();
              avatar_url = e.target.result;
            }); 
            
            FR.readAsDataURL( this.files[0] );
          }
          
        }
        function saveFormData(url, btnEl, method_type){
           if( !Validate()) return false;

            // check for required fields
            if(!checkRequiredFields(btnEl.parents('form'))) return false;

            var array = btnEl.parents('form').serializeArray();
            var from_data = {};
            jQuery.each(array, function () {
                from_data[this.name] = this.value || '';
            });
            from_data['avatar'] = avatar_url;
            $.ajax({
               type: method_type,
               url: url,
               headers: {'Authorization': "Token {{request|getToken}}", 'Content-Type': 'application/json'},
               data: JSON.stringify(from_data),
               success: function (data) {
                   $.toaster({priority: 'success', title: 'Success', message:'User Info Updated!' });
                    if(btnEl.hasClass('next')){
                        $('a[href="#user_profile"]').tab('show');
                    }
                    else{
                        //window.location.href = "{% url 'users_listing' %}";
                    }
                },
                error:function(data){
                    data = data.responseJSON;
                    message = '';
                    try{
                        if(typeof data['email'] !== 'undefined'){
                            message += '<br>Email: '+data['email'][0];
                        }
                        
                        if(typeof data['username'] !== 'undefined'){
                            message += '<br>Username: '+data['username'][0];
                        }
                        $.toaster({ priority : 'danger', title : 'Error', message : message});
                    } catch(e) {
                        $.toaster({priority: 'danger', title: 'Error', message:'Error Occur!' });
                    }
                }
            });
        }
        jQuery(document).on('click','.save-basic',function(e){
            e.preventDefault();
            {% if user_obj %}
                var url = "{% url app_url %}"+'/'+"{{user_obj.id}}"+'/';
            {% else %}
                var url = "{% url app_url %}";
            {% endif %}
            var method_type = "{{type}}";
            saveFormData(url, $(this), method_type);
        })
        jQuery(document).on('click','.save-profile',function(e){
            e.preventDefault();
            {% if profile is not None %}
                var profile_url = "{% url 'profiles' %}"+'/'+"{{user_obj.id}}"+'/';
                var method_type = 'PUT';
            {% else %}
                var method_type = 'POST';
                var profile_url = "{% url 'profiles' %}";
            {% endif %}
            saveFormData(profile_url, $(this), method_type);
        })

        document.getElementById("id_avatar").addEventListener("change", readFile);
    });
</script>
{% endblock %}

users/templates/users/user/listing.html
{% extends "users/base.html" %}
{% load static %}

{% block content %}

<div class="container-fluid">
    <!-- Row Starts -->
    <div class="row">
        <div class="col-sm-12 p-0">
            <div class="main-header">
                <h4>Users</h4>
                <ol class="breadcrumb breadcrumb-title breadcrumb-arrow">
                    <li class="breadcrumb-item"><a href="/"><i class="icofont icofont-home"></i></a>
                    </li>
                    <li class="breadcrumb-item"><a href="#">Users</a>
                    </li>
                </ol>
            </div>
        </div>
    </div>
    <!-- Row end -->

    <!-- Row Starts -->
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                     <h5 class="card-header-text">Users List</h5></div>
                <div class="card-block">
                    <div class="table-responsive" data-pattern="priority-columns">
                        <table cellspacing="0" id="albums"  class="datatable table table-small-font table-bordered table-striped">
                            <thead>
                            <tr>
                                <th data-priority="1">ID</th>
                                <th data-priority="2">Username</th>
                                <th data-priority="3">First Name</th>
                                <th data-priority="4">Last Name</th>
                                <th data-priority="5">Email</th>
                                <th data-priority="5">Type</th>
                                <th data-priority="6">Status</th>
                                <th data-priority="6">Action</th>

                            </tr>
                            </thead>

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Row end -->
</div>
{% endblock %}
{% block footer %}
<script>
    jQuery(document).ready(function($) {
        var table = $('#albums').DataTable({
            "serverSide": true,
            "responsive": true,
            "ajax":{
                url:"api/users?format=datatables", headers: { 'Authorization': 'Token {{request|getToken}}' },
            },
            "columns": [
                {"data": "id", "searchable": false},
                {"data": "username"},
                {"data": "first_name"},
                {"data": "last_name"},
                {"data": "email"},
                {
                    data: "groups",
                    render: function ( data, type, row ) {
                        var groups = [];
                        $.each(data, function(key, value) {
                            groups.push(value.name);
                        });
                        return  groups ;
                    }
                },
                {
                    data: "is_active",
                    render: function ( data, type, row, meta ) {
                        var status,StatusClass = '';
                        if(row.is_active === true ){
                            status = 'Active';
                            StatusClass='btn-success';
                        }else{
                            status = 'In-Active';
                            StatusClass='btn-danger';
                        }
                        return '<a href="api/users/'+row.id+'/" data-status="'+row.is_active+'"  class="tabledit-status-button btn btn-mini waves-effect waves-light '+StatusClass+'">'+ status +'</a>';
                    }
                },
                {
                    data: "action",
                    render: function ( data, type, row, meta ) {
                        return '<a href="users/'+row.id+'/"  class="tabledit-edit-button btn btn-mini btn-primary waves-effect waves-light"><span class="icofont icofont-ui-edit"></span></a>' +
                                '<a  href="api/users/'+row.id+'/"  class="tabledit-delete-button btn btn-mini btn-danger waves-effect waves-light"><span class="icofont icofont-ui-delete"></span></a>';
                    }
                },
            ],
        });
        $(document).on('click','.tabledit-delete-button',function(e){
            e.preventDefault();
            var url ='';
            url = $(this).attr("href");
            $.ajax({
                type:'DELETE',
                url:url,
                headers: { 'Authorization': "Token {{request|getToken}}",'Content-Type': 'application/json'},
                success:function(data){
                    table.draw(false);
                    $.toaster({ priority : 'success', title : 'Status', message : 'User Deleted!'});
                }
            });
        })
        $(document).on('click','.tabledit-status-button',function(e){
            e.preventDefault();
            var url ='';
            url = $(this).attr("href");
            status = $(this).data("status");
            status = status == 'true' ? status = false : status = true;
            $.ajax({
                type:'PATCH',
                url:url,
                headers: { 'Authorization': "Token {{request|getToken}}",'Content-Type': 'application/json'},
                data:JSON.stringify({ "is_active": status }),
                success:function(data){
                    table.draw(false);
                    $.toaster({ priority : 'success', title : 'Status', message : 'User Status Updated!'});
                }
            });
        })

        searchOrderFn(table);
    });
</script>

{% endblock %}