api/urls.py
from rest_framework.urlpatterns import format_suffix_patterns
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from hospital import views as hospital_view
from users import views as users_view
from django.conf.urls import url

# Create a router and register our viewsets with it.

router = DefaultRouter()

u_list = users_view.UserViewSet.as_view({
    'get': 'list',
    'post': 'create'
})
user_detail = users_view.UserViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})
profile_list = users_view.ProfileViewSet.as_view({
    'get': 'list',
    'post': 'create'
})
profile_detail = users_view.ProfileViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})
hospitals_list = hospital_view.HospitalsViewSet.as_view({
    'get': 'list',
    'post': 'create'
})
hospitals_detail = hospital_view.HospitalsViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})

student_list = users_view.StudentViewSet.as_view({
    'get': 'list',
    'post': 'create'
})
student_detail = users_view.StudentViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})
appointments_list = users_view.AppointmentsViewSet.as_view({
    'get': 'list',
    'post': 'create'
})
appointments_detail = users_view.AppointmentsViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})
prescriptions_list = users_view.PrescriptionViewSet.as_view({
    'get': 'list',
    'post': 'create'
})
prescriptions_detail = users_view.PrescriptionViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})
doctor_list = users_view.DoctorsViewSet.as_view({
    'get': 'list',
    'post': 'create'
})
doctor_detail = users_view.DoctorsViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})
# The API URLs are now determined automatically by the router.
urlpatterns = format_suffix_patterns([
    path('', users_view.api_root),
    path('hospitals', hospitals_list, name='hospitals'),
    path('hospitals/<pk>/', hospitals_detail),
    path('students', student_list, name='students'),
    path('students/<pk>/', student_detail),
    path('doctors', doctor_list, name='doctors'),
    path('doctors/<pk>/', doctor_detail),
    path('users', u_list, name='users'),
    path('users/<pk>/', user_detail),
    path('profiles', profile_list, name='profiles'),
    path('profiles/<pk>/', profile_detail),
    path('appointments', appointments_list, name='appointments'),
    path('appointments/<pk>/', appointments_detail),
    path('prescriptions', prescriptions_list, name='prescriptions'),
    path('prescriptions/<pk>/', prescriptions_detail),
])

restapi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views # for login logout
from .views import login, sample_api, loginPage, logout
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('hospital.urls')),
    path('api/', include('api.urls')),
    path('api/login', login, name='api_login'),
    path('', loginPage),
    path('login', loginPage),

    path('api/sampleapi', sample_api),

    # path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('logout/', logout, name='logout'),

]
urlpatterns += [
    path('api-auth/', include('rest_framework.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from rest_framework.urlpatterns import format_suffix_patterns
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views
from django.conf.urls import url

urlpatterns = format_suffix_patterns([
    path('users-list', views.users_listing, name='users_listing'),
    path('users/add', views.add_user, name='add_user'),
    path('users/<int:id>/', views.edit_user, name='edit_user'),
    path('users/profile/<int:id>/', views.user_profile, name='user_profile'),
    path('users-dashboard', views.users_dashboard, name='users_dashboard'),
    path('appointment/add', views.add_appointment, name='add_appointment'),
    path('appointments-list', views.appointments_listing, name='appointments_listing'),
    path('appointments-schedule/', views.AppointmentCalendar.as_view(), name='appointments_schedule'),
    path('appointments/<int:id>/', views.appointment_detail, name='appointment_detail_page'),
    path('appointments/edit/<int:id>/', views.edit_appointment, name='edit_appointment'),
    #path('appointments/<int:appointment_id>/prescriptions/add/',views.add_prescriptions, name='add_prescriptions'),
    path('appointments/<int:appointment_id>/prescriptions/add/',views.add_prescriptions_info, name='add_prescriptions_info'),
    path('save_prescriptions_info/',views.save_prescriptions_info, name='save_prescriptions_info'),
    path('delete_prescriptions_info/',views.delete_prescriptions_info, name='delete_prescriptions_info'),
    path('prescriptions-list', views.prescriptions_listings, name='prescriptions_listing'),
    path('prescriptions/add', views.add_prescriptions, name='add_prescriptionsfordoctor'),


    path('prescriptions/<int:id>/', views.prescriptions_detail, name='prescriptions_detail_page'),
    path('prescriptions/<int:id>/edit/', views.edit_prescriptions, name='edit_prescriptions'),
])

users/models.py
from django.db import models
from pygments.lexers import get_all_lexers
from pygments.styles import get_all_styles
from django.contrib.auth.models import User
from pygments.lexers import get_lexer_by_name
from pygments.formatters.html import HtmlFormatter
from PIL import Image # resize image

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
	title = models.CharField(max_length=100, blank=True, null=True)
	GENDER_CHOICES = (
		('male', 'Male'),
		('female', 'Female'),
	)
	gender = models.CharField(choices=GENDER_CHOICES, blank=True, null=True, max_length=10)
	designation =  models.CharField(max_length=250, blank=True, null=True)
	qualification = models.CharField(max_length=250, blank=True, null=True)
	experience = models.CharField(max_length=250, blank=True, null=True)
	primary_hospital = models.ForeignKey("hospital.Hospital", on_delete=models.SET_NULL, blank=True, null=True)                                    
	secondary_hospital = models.ForeignKey("hospital.Hospital", on_delete=models.SET_NULL, related_name='secondary_hospital',blank=True, null=True)                                    
	specialty = models.CharField(max_length=250, blank=True, null=True)
	mobile_no = models.CharField(max_length=25, blank=True, null=True)
	session_1_start = models.TimeField(null=True, blank=True)
	session_1_end = models.TimeField(null=True, blank=True)
	session_2_start = models.TimeField(null=True, blank=True)
	session_2_end = models.TimeField(null=True, blank=True)
	avatar = models.ImageField(default='default.png',upload_to='profile')
	MARTIAL_STATUS = (
		('married', 'Married'),
		('unmarried', 'Unmarried'),
		('windowed', 'Widowed'),
	)
	martial_status = models.CharField(choices=MARTIAL_STATUS, blank=True, null=True, max_length=10)
	weight = models.CharField(max_length=250, blank=True, null=True)
	height = models.CharField(max_length=250, blank=True, null=True)
	diseases  = models.CharField(max_length=250, blank=True, null=True)
	allergies = models.CharField(max_length=250, blank=True, null=True)
	BLOOD_TYPES = (
		('O+', 'O-Positive'),
		('O-', 'O-Negative'),
		('A+', 'A-Positive'),
		('A-', 'A-Negative'),
		('AB+', 'AB-Positive'),
		('AB-', 'AB-Negative'),
	)
	blood_type = models.CharField(choices=BLOOD_TYPES, blank=True, null=True, max_length=4)
	notes = models.TextField(blank=True, null=True)
	created_date = models.DateTimeField(auto_now_add=True)
	modified_date = models.DateTimeField(auto_now=True)
	class Meta:
		ordering = ('created_date',)

	def __str__(self): # converting obj
		return f'{self.user.username} Profile'



class Appointment(models.Model):
	student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='student')    
	doctor = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='doctor', blank=True, null=True)
	refer_to = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='refer_to', blank=True, null=True)
	datetime = models.DateTimeField()
	disease = models.TextField()
	notes = models.TextField(blank=True, null=True)
	STATUS_CHOICES = (
		('N', 'New'),
		('P', 'Processed'),
		('C', 'Cancel'),
	)
	status = models.CharField(choices=STATUS_CHOICES, max_length=2, default='N')
	# status = models.BooleanField(default=True)
	created_date = models.DateTimeField(auto_now_add=True)
	modified_date = models.DateTimeField(auto_now=True)
	def __str__(self): # converted obj
		return f'{self.student.username}- App. # {self.id}'


class Prescription(models.Model):
	appointment = models.OneToOneField(Appointment, on_delete=models.CASCADE, primary_key=True)
	how_to_use = models.TextField(blank=True, null=True)
	medicine_name = models.CharField(max_length=250, blank=True, null=True)
	medicine_type = models.ForeignKey("hospital.MedicineType", on_delete=models.SET_NULL, blank=True, null=True)
	edit_by = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='edit_by', blank=True, null=True)
	created_date = models.DateTimeField(auto_now_add=True)
	modified_date = models.DateTimeField(auto_now=True)
	def __str__(self): # convert obj
		managed = False
		return f'{self.appointment.student.username} Appointment with {self.appointment.doctor.username} '

class Prescription_info(models.Model):
	appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE, related_name='appointment')
	how_to_use = models.TextField(blank=True, null=True)
	medicine_name = models.CharField(max_length=250, blank=True, null=True)
	medicine_type = models.ForeignKey("hospital.MedicineType", on_delete=models.SET_NULL, blank=True, null=True)
	created_date = models.DateTimeField(auto_now_add=True)
	edit_by = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='edit_user', blank=True, null=True)
	modified_date = models.DateTimeField(auto_now=True)
	def __str__(self): # convert obj
		managed = False
		return f'{self.medicine_name}'
	

users/templates/users/appointments/calendar.html
{% extends "users/base.html" %}
{% load static %}

{% block content %}
<!-- Calender css -->

<link rel="stylesheet" type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.0/fullcalendar.min.css">

<link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.0/fullcalendar.print.min.css " rel="stylesheet"
      type="text/css" media="print"/>
<style>
    a.fc-day-grid-event.fc-h-event.fc-event.fc-start.fc-end {
        border-color: rgb(57, 68, 78) !important;
        padding: 4px;
        bottom: auto !important;
    }

    a.fc-time-grid-event.fc-v-event.fc-event.fc-start.fc-resizable {
        bottom: auto !important;
        background-color: #39444e;
        border: none;
        color: white
    }

    /*.fc-time-grid-event .fc-content{background-color: #3a87ad;padding:4px;}*/
    .tooltiptopicevent {
        width: auto;
        height: auto;
        background-color: #39444e;
        position: absolute;
        z-index: 10001;
        padding: 10px 10px 10px 10px;
        line-height: 200%;
        border-radius: 5px;
        color: white
    }

    .fc-time-grid-event.fc-v-event.fc-event.fc-start.fc-end {
        bottom: auto !important;
    }
</style>
<!-- Container-fluid starts -->
<div class="container-fluid">
    <div>
        <!-- Header Starts -->
        <div class="row">
            <div class="col-sm-12 p-0">
                <div class="main-header">
                    <h4>Appointments</h4>{{request.test}}
                    <ol class="breadcrumb breadcrumb-title breadcrumb-arrow">
                        <li class="breadcrumb-item"><a href="/"><i class="icofont icofont-home"></i></a>
                        </li>
                        <li class="breadcrumb-item"><a href="#">Appointments</a>
                        </li>
                    </ol>
                    <div style="right: 15px;position: absolute;bottom: 12px;">
                        <a href="{% url 'appointments_listing' %}"
                           class="btn btn-mini btn-primary waves-effect waves-light">Listing View</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Header end -->

        <!-- Row start -->
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-block">
                        <div class="row">
                            <div class="col-md-12">
                                <div id='calendar'></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Row end -->

    </div>

</div>
{% endblock %}

{% block footer %}

<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.0/fullcalendar.min.js"></script>
<script>
    "use strict";
    $(document).ready(function () {
        $('#external-events .fc-event').each(function () {

            // store data so the calendar knows to render an event upon drop
            $(this).data('event', {
                title: $.trim($(this).text()), // use the element's text as the event title
                stick: true // maintain when user navigates (see docs on the renderEvent method)
            });

            // make the event draggable using jQuery UI
            /*   $(this).draggable({
             zIndex: 999,
             revert: true,      // will cause the event to go back to its
             revertDuration: 0  //  original position after the drag
             });*/

        });

        $('#calendar').fullCalendar({
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay,listMonth'
            },
            defaultDate: '{% now "Y-m-d" %}',
            navLinks: true, // can click day/week names to navigate views
            businessHours: true, // display business hours
            // editable: true,
            // droppable: true, // this allows things to be dropped onto the calendar
            disableDragging: true,
            drop: function () {

                // is the "remove after drop" checkbox checked?
                if ($('#checkbox2').is(':checked')) {
                    // if so, remove the element from the "Draggable Events" list
                    $(this).remove();
                }
            },
            eventMouseover: function (data, event, view) {
                var tooltip = '<div class="tooltiptopicevent">' + 'Student ' + ': ' + data.student + '</br>';
                {% if request|isSuperAdmin %}
                tooltip += 'Doctor: ' + data.doctor + '</br>';
                {% endif %}
                tooltip += 'Created ' + ': ' + data.created + '</br>' + 'Notes ' + ': ' + data.notes + '</div>';


                $("body").append(tooltip);
                $(this).mouseover(function (e) {
                    $(this).css('z-index', 10000);
                    $('.tooltiptopicevent').fadeIn('500');
                    $('.tooltiptopicevent').fadeTo('10', 1.9);
                }).mousemove(function (e) {
                    $('.tooltiptopicevent').css('top', e.pageY + 10);
                    $('.tooltiptopicevent').css('left', e.pageX + 20);
                });


            },
            eventMouseout: function (data, event, view) {
                $(this).css('z-index', 8);

                $('.tooltiptopicevent').remove();

            },
            dayClick: function () {
                tooltip.hide()
            },
            eventResizeStart: function () {
                tooltip.hide()
            },
            eventDragStart: function () {
                tooltip.hide()
            },
            viewDisplay: function () {
                tooltip.hide()
            },
            eventClick: function (event) {
                window.location.assign('/appointments/' + event.id);
            },
            events: [
            {% for appointment in appointments %}
        {
            start: '{{ appointment.datetime }}',
                    textColor
        :
            '#000',
            {% if appointment.status == 'N' %}
            title: "App # {{ appointment.id}}",
                    backgroundColor
        :
            '#3a87ad'
            {% else %}
            title: "App # {{ appointment.id}} - Assigned",
                    backgroundColor
        :
            '#5ecd5e'
            {% endif %}
        ,
            id: '{{appointment.id}}',
                    student
        :
            '{{appointment.student.username}}',
                    doctor
        :
            '{{appointment.doctor.username}}',
                    notes
        :
            '{{appointment.notes}}',
                    created
        :
            '{{appointment.created_date}}',
        }
        ,
        {% endfor %}
        ]
    })
        ;

    });

</script>

{% endblock %}

users/templates/users/appointments/form.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 p-0">
            <div class="main-header">
                <h4>{{ app|capfirst }}</h4>
                <ol class="breadcrumb breadcrumb-title breadcrumb-arrow">
                    <li class="breadcrumb-item"><a href="/"><i class="icofont icofont-home"></i></a>
                    </li>
                    <li class="breadcrumb-item"><a href="{% url 'appointments_listing' %}">{{ app|capfirst }}   </a>
                    </li>
                </ol>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <form method="POST" class="form" action="">
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">{% if obj.id  %} Edit  {{ app|capfirst }}  {% else %} Add {{ app|capfirst }} {% endif %}  </legend>
                           {% crispy form %}
                           <div class="form-group">
                                <button class="btn btn-info save-basic" type="submit">Save </button>
                                <p class="text-danger" id="error"> </p>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block footer %}
<script>

    jQuery(document).ready(function($) {
        var existing_tags = [];
         {% for tag in tags %}
            console.log('{{tag}}');
            console.log('test');
            existing_tags += '<option value="{{tag}}" selected="selected">{{tag}}</option>';
        {% endfor %}
       
        $('#id_disease').html(existing_tags);
        $('#id_disease').select2();

        function saveFormData(url, btnEl, method_type){
           // if( Validate() === true ) {
            var array = btnEl.parents('form').serializeArray();
            var from_data = {};
            jQuery.each(array, function () {
                if(this.name == 'disease'){
                    if(from_data[this.name])
                        from_data[this.name].push(this.value);
                    else
                        from_data[this.name] = [this.value];
                } 
                else
                    from_data[this.name] = this.value || '';
            });

            from_data['disease'] = JSON.stringify(from_data['disease'])

            console.log(from_data);
            $.ajax({
               type: method_type,
               url: url,
               headers: {'Authorization': "Token {{request|getToken}}", 'Content-Type': 'application/json'},
               data: JSON.stringify(from_data),
               success: function (data) {
                   $.toaster({ priority : 'success', title : 'Success', message : 'Appointment Updated!'});

                   window.location.href = "{% url 'appointments_listing' %}";

                },

                error:function(data){
                    data = data.responseJSON;
                    message = '';
                    try{
                        if(typeof data['non_field_errors'] !== 'undefined'){
                            message += '<br>'+data['non_field_errors'][0];
                        }
                        if(typeof data['disease'] !== 'undefined'){
                            message += '<br>Disease:'+data['disease'][0];
                        }
                        $.toaster({ priority : 'danger', title : 'Error', message : message});
                    } catch(e) {
                        $.toaster({priority: 'danger', title: 'Error', message:'Error Occur!' });
                    }
                }
            });
        }

        jQuery(document).on('click','.save-basic',function(e){
            e.preventDefault();
            {% if obj.id %}
                var url = "{% url app_url %}"+'/'+"{{obj.id}}"+'/';
            {% else %}
                var url = "{% url app_url %}";
            {% endif %}
            var method_type = "{{type}}";
            saveFormData(url, $(this), method_type);
        })

    });
</script>
{% endblock %}

users/templates/users/appointments/listing.html
{% extends "users/base.html" %}
{% load static %}

{% block content %}

<div class="container-fluid">
    <!-- Row Starts -->
    <div class="row">
        <div class="col-sm-12 p-0">
            <div class="main-header">
                <h4>Appointments</h4>
                <ol class="breadcrumb breadcrumb-title breadcrumb-arrow">
                    <li class="breadcrumb-item"><a href="/"><i class="icofont icofont-home"></i></a>
                    </li>
                    <li class="breadcrumb-item"><a href="#!">Appointments</a>
                    </li>
                </ol>
                <div style="right: 15px;position: absolute;bottom: 12px;">
                    <a href="{% url 'appointments_schedule' %}"
                       class="btn btn-mini btn-primary waves-effect waves-light">Calendar View</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Row end -->

    <!-- Row Starts -->
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-header-text">Appointments List</h5></div>
                <div class="card-block">
                    <div class="table-responsive" data-pattern="priority-columns">
                        <table cellspacing="0" id="appointments"  class="datatable table table-small-font table-bordered table-striped">
                            <thead>
                            <tr>
                                <th data-priority="1">ID</th>
                                <th data-priority="2">Student</th>
                                {% if request|isDoctor %}
                                    <th data-priority="2">Refer By</th>
                                {% endif %}
                                {% if not request|isDoctor %}
                                     <th data-priority="6">Doctor</th>
                                     <th data-priority="2">Refer To</th>
                                {% endif %}
                                <th data-priority="6">Date Time</th>
                                <th data-priority="6">Disease</th>
                                <th data-priority="6">Notes</th>
                                {% if not request|isDoctor %}
                                    <!--<th data-priority="6">Status</th>-->
                                {% endif %}
                                <th data-priority="6">Action</th>
                            </tr>
                            </thead>

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Row end -->
</div>
{% endblock %}
{% block footer %}
<script>
    jQuery(document).ready(function($) {
        {% if not request|isDoctor %}
        var table = $('#appointments').DataTable({
            "serverSide": true,
            "responsive": true,
            "ajax":{
                url:"api/appointments?format=datatables",
                headers: { 'Authorization': 'Token {{request|getToken}}' },
                },
            "columns": [
                {"data": "id", "searchable": false},
                {"data": "student"},
                {"data": "doctor"},
                {
                    data: "refer_to_name",
                    render: function(data, type, row){
                        return  row.refer_to_name &&  row.refer_to_name != row.doctor ? row.refer_to_name : '';
                    }
                },
                {"data": "datetime"},
                {"data": "disease"},
                {"data": "notes"},
//                {
//                    data: "status",
//                    render: function ( data, type, row, meta ) {
//                        var status,StatusClass = '';
//                        if(row.status === true ){
//                            status = 'Active';
//                            StatusClass='btn-success';
//                        }else{
//                            status = 'In-Active';
//                            StatusClass='btn-danger';
//                        }
//                        return '<button class="tabledit-edit-button btn btn-mini waves-effect waves-light '+StatusClass+'">'+ status +'</button>';
//                    }
//                },
                {
                    data: "action",
                    render: function ( data, type, row, meta ) {
                        return '<a href="/appointments/'+row.id+'/" class="tabledit-edit-button btn btn-mini btn-primary waves-effect waves-light"><span class="icofont icofont-open-eye"></span></a>'+
                                '<a href="appointments/edit/'+row.id+'/"  class="tabledit-edit-button btn btn-mini btn-primary waves-effect waves-light"><span class="icofont icofont-ui-edit"></span></a>' +
                                '<a  href="api/appointments/'+row.id+'/"  class="tabledit-delete-button btn btn-mini btn-danger waves-effect waves-light"><span class="icofont icofont-ui-delete"></span></a>';
                    }
                },

            ],
        });
        {% else %}
        var table = $('#appointments').DataTable({
            "serverSide": true,
            "responsive": true,
            "ajax":{
                url:"api/appointments?format=datatables",
                headers: { 'Authorization': 'Token {{request|getToken}}' },
                },
            "columns": [
                {"data": "id", "searchable": false},
                {"data": "student"},

                {
                    data: "doctor",
                    render: function(data, type, row ){
                        return  row.doctor && row.doctor !=  "{{ request|getUser:'username' }}"  ? row.doctor : '';
                    }
                },
                {"data": "datetime"},
                {"data": "disease"},
                {"data": "notes"},
                {
                    data: "action",
                    render: function ( data, type, row, meta ) {
                        return '<a href="/appointments/'+row.id+'/" class="tabledit-edit-button btn btn-mini btn-primary waves-effect waves-light"><span class="icofont icofont-open-eye"></span></a>';
                    }
                },

            ],
        });
        {% endif %}
        searchOrderFn(table);

        $(document).on('click','.tabledit-delete-button',function(e){
            e.preventDefault();
            var url ='';
            url = $(this).attr("href");
            $.ajax({
                type:'DELETE',
                url:url,
                headers: { 'Authorization': "Token {{request|getToken}}",'Content-Type': 'application/json'},
                success:function(data){
                    table.draw(false);
                    $.toaster({ priority : 'success', title : 'Status', message : 'Appointment Deleted!'});
                }
            });
        })
    });
</script>

{% endblock %}